const CONFIG={businessName:"PS CENTER",whatsapp:"6281234567890",catalogUrl:window.location.href,currency:"Rp"};
const games=[
{id:1,title:"GTA V",genre:"Action",players:"1–2 Player",price:10000,status:"Tersedia",cover:"covers/gta-v.svg",desc:"Open-world action dengan mode story dan multiplayer."},
{id:2,title:"EA SPORTS FC 24",genre:"Sport",players:"1–4 Player",price:10000,status:"Tersedia",cover:"covers/fc24.svg",desc:"Main sepak bola bersama teman dengan berbagai mode pertandingan."},
{id:3,title:"God of War Ragnarök",genre:"Adventure",players:"1 Player",price:12000,status:"Tersedia",cover:"covers/god-of-war.svg",desc:"Petualangan epik Kratos dan Atreus dalam perjalanan melintasi dunia Norse."},
{id:4,title:"Marvel's Spider-Man",genre:"Action",players:"1 Player",price:12000,status:"Tersedia",cover:"covers/spiderman.svg",desc:"Ayunkan jaring, jelajahi New York, dan hadapi para penjahat ikonik."},
{id:5,title:"Red Dead Redemption 2",genre:"Adventure",players:"1 Player",price:12000,status:"Tersedia",cover:"covers/rdr2.svg",desc:"Petualangan western dengan dunia terbuka yang luas dan cerita sinematik."},
{id:6,title:"Tekken 7",genre:"Fighting",players:"1–2 Player",price:10000,status:"Tersedia",cover:"covers/tekken7.svg",desc:"Pertarungan versus yang cocok dimainkan ramai-ramai."},
{id:7,title:"Resident Evil 4",genre:"Horror",players:"1 Player",price:12000,status:"Tersedia",cover:"covers/re4.svg",desc:"Survival horror penuh aksi dan suasana menegangkan."},
{id:8,title:"Need for Speed Heat",genre:"Racing",players:"1–2 Player",price:10000,status:"Tersedia",cover:"covers/nfs.svg",desc:"Balapan jalanan siang dan malam dengan mobil yang bisa dikustomisasi."}];
const $=s=>document.querySelector(s),money=n=>CONFIG.currency+" "+n.toLocaleString("id-ID");
function waLink(g){return "https://wa.me/"+CONFIG.whatsapp+"?text="+encodeURIComponent("Halo "+CONFIG.businessName+", saya mau rental game "+g.title+". Apakah masih tersedia?")}
function renderCategories(){const cats=["Semua",...new Set(games.map(g=>g.genre))];$("#categories").innerHTML=cats.map((c,i)=>'<button class="cat '+(i===0?"active":"")+'" data-cat="'+c+'">'+c+"</button>").join("");document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{document.querySelectorAll(".cat").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()})}
function render(){const q=$("#search").value.toLowerCase(),cat=document.querySelector(".cat.active")?.dataset.cat||"Semua",list=games.filter(g=>(cat==="Semua"||g.genre===cat)&&(g.title+" "+g.genre).toLowerCase().includes(q));$("#count").textContent=list.length+" game";$("#gameGrid").innerHTML=list.map(g=>'<article class="game" onclick="openGame('+g.id+')"><div class="cover"><img src="'+g.cover+'" alt="Cover '+g.title+'"><span class="status available">'+g.status+'</span></div><div class="game-info"><h3>'+g.title+'</h3><div class="meta"><span>'+g.genre+'</span><span class="price">'+money(g.price)+'</span></div><button class="rent" onclick="event.stopPropagation();window.open(\''+waLink(g)+'\',\'_blank\')">Rental via WA</button></div></article>').join("")}
window.openGame=id=>{const g=games.find(x=>x.id===id);$("#modalCover").src=g.cover;$("#modalCover").alt=g.title;$("#modalGenre").textContent=g.genre.toUpperCase();$("#modalTitle").textContent=g.title;$("#modalDesc").textContent=g.desc;$("#modalPlayers").textContent="👥 "+g.players;$("#modalPrice").textContent=money(g.price);$("#modalWA").href=waLink(g);$("#modal").classList.add("show")};
function makeQR(el,size){el.innerHTML="";if(window.QRCode)new QRCode(el,{text:CONFIG.catalogUrl,width:size,height:size,colorDark:"#000000",colorLight:"#ffffff"})}
$("#search").addEventListener("input",render);$("#close").onclick=()=>$("#modal").classList.remove("show");$("#modal").onclick=e=>{if(e.target.id==="modal")$("#modal").classList.remove("show")};$("#showQR").onclick=()=>$("#qrModal").classList.add("show");$("#closeQR").onclick=()=>$("#qrModal").classList.remove("show");$("#qrModal").onclick=e=>{if(e.target.id==="qrModal")$("#qrModal").classList.remove("show")};$("#waTop").href="https://wa.me/"+CONFIG.whatsapp+"?text="+encodeURIComponent("Halo PS CENTER, saya mau tanya katalog game PS4.");$("#year").textContent=new Date().getFullYear();renderCategories();render();makeQR($("#qrcode"),190);makeQR($("#qrcodeBig"),250);